import { Button } from "@/components/ui/button";
import { Globe } from "@/components/ui/globe";
import { Navbar } from "@/components/navbar";
import { BentoGrid, BentoCard } from "@/components/ui/bento-grid";
import { Marquee } from "@/components/ui/marquee";
import { FileText, Globe as GlobeIcon, ShieldCheck } from "lucide-react";
import React from "react";
import { ShinyButton } from "@/components/ui/shiny-button"; // Import the new button

// --- Data for Features & Testimonials (remains the same) ---
const features = [
  { Icon: FileText, name: "Synthetic Data Generation", description: "Generate statistically accurate, anonymous patient data.", className: "col-span-3 lg:col-span-1", background: <img className="absolute -right-20 -top-20 opacity-60" /> },
  { Icon: GlobeIcon, name: "Interactive Timelines", description: "Explore and model what-if scenarios on patient journeys.", className: "col-span-3 lg:col-span-2", background: <img className="absolute -right-20 -top-20 opacity-60" /> },
  { Icon: ShieldCheck, name: "Privacy First", description: "Analyze rich data without ever compromising patient privacy.", className: "col-span-3 lg:col-span-2", background: <img className="absolute -right-20 -top-20 opacity-60" /> },
  { Icon: FileText, name: "Data Marketplace", description: "Request specific datasets to be generated by institutions.", className: "col-span-3 lg:col-span-1", background: <img className="absolute -right-20 -top-20 opacity-60" /> },
];
const testimonials = [
  { name: "Dr. Aris Thorne", title: "Head of Computational Biology", body: "Synthify has revolutionized our research process. We can now test hypotheses in days, not months, all while ensuring absolute patient confidentiality." },
  { name: "Elena Vostok", title: "Senior Data Scientist", body: "The ability to generate and interact with synthetic patient timelines is a game-changer. The 'what-if' scenarios have unlocked insights we never thought possible." },
];

const ReviewCard = ({ name, title, body }: { name: string; title: string; body: React.ReactNode; }) => {
  return (
    <div className="relative w-64 h-full cursor-pointer overflow-hidden rounded-xl border p-4">
      <div className="flex flex-col justify-between h-full"><div className="text-sm font-normal text-neutral-500">{body}</div><div className="mt-4"><p className="text-sm font-medium text-black">{name}</p><p className="text-xs font-normal text-neutral-400">{title}</p></div></div>
    </div>
  );
};

export function LandingPage() {
  return (
    <div className="w-full bg-white text-black">
      <Navbar />
      
      {/* --- Hero Section --- */}
      <div className="h-screen w-full flex flex-col items-center justify-center text-center px-4 pt-20">
        <h1 className="text-5xl md:text-7xl font-bold bg-clip-text text-transparent bg-gradient-to-b from-black to-neutral-600">Secure Insights, Synthesized</h1>
        <p className="mt-4 text-base text-neutral-500 max-w-lg">Analyze rich patient data without compromising privacy. Welcome to the future of medical research.</p>
        <div className="relative flex h-96 w-full max-w-5xl items-center justify-center -mt-8"><Globe /></div>
        <div className="flex flex-col md:flex-row items-center gap-4 -mt-8"><Button size="lg">Sign up as Researcher</Button><Button size="lg" variant="secondary">Sign up as Hospital Admin</Button></div>
      </div>

      {/* --- Features Section --- */}
      <div className="px-4 pt-24 pb-8">
        <h2 className="text-4xl font-bold text-center mb-10">A New Paradigm in Research</h2>
        <BentoGrid className="lg:grid-rows-2 max-w-4xl mx-auto">{features.map((feature, idx) => (<BentoCard href={""} cta={""} key={idx} {...feature} />))}</BentoGrid>
      </div>

      {/* --- NEW: Call to Action Section --- */}
      <div className="py-12 px-4 text-center">
        <h2 className="text-4xl font-bold mb-4">Ready to Revolutionize Your Research?</h2>
        <p className="text-neutral-500 max-w-xl mx-auto mb-8">Join the platform that's setting a new standard for data security and research efficiency. Get started in minutes.</p>
        <ShinyButton>Get Started Today</ShinyButton>
      </div>

      {/* --- Testimonials Section --- */}
      <div className="pb-12">
        <h2 className="text-4xl font-bold text-center mb-10">Trusted by Leading Institutions</h2>
        <div className="relative flex h-full w-full flex-col items-center justify-center overflow-hidden"><Marquee pauseOnHover className="[--duration:20s]">{testimonials.map((review) => (<ReviewCard key={review.name} {...review} />))}</Marquee></div>
      </div>
      
      {/* --- NEW: Footer --- */}
      <footer className="w-full bg-slate-900 text-slate-400 py-8 px-4">
        <div className="max-w-7xl mx-auto flex justify-between items-center text-sm">
          <p>&copy; {new Date().getFullYear()} Synthify. All rights reserved.</p>
          <div className="flex gap-4">
            <a href="#" className="hover:text-white">Terms of Service</a>
            <a href="#" className="hover:text-white">Privacy Policy</a>
          </div>
        </div>
      </footer>
    </div>
  );
}